apiVersion: v1
kind: Pod
metadata:
  name: nodejs-app-demo-k8s-hpa-pod
  labels:
    app: nodejs-app-demo-k8s-hpa
spec:
  # imagePullSecrets:
  #   - name: sample-docker-secret
  containers:
    - name: nodejs-app-demo-k8s-hpa
      image: sdubey321/nodejs-app-demo-k8s-hpa:1.0.0
      ports:
        - containerPort: 3000
      env:
        - name: DB_PASSWORD_NODE_DEMO
          valueFrom:
            secretKeyRef:
              key: password
              name: nodejs-app-demo-k8s-hpa-secret
        - name: KEY1
          valueFrom:
            secretKeyRef:
              key: key1
              name: nodejs-app-demo-k8s-hpa-secret
        - name: KEY2
          valueFrom:
            secretKeyRef:
              key: key2
              name: nodejs-app-demo-k8s-hpa-secret
        - name: PORT
          valueFrom:
            configMapKeyRef:
              key: PORT_FROM_CONFIGMAP
              name: nodejs-app-demo-k8s-hpa-configmap
        - name: APP_NAME
          valueFrom:
            configMapKeyRef:
              key: APP_NAME_FORM_CONFIGMAP
              name: nodejs-app-demo-k8s-hpa-configmap
        - name: CONFIGMAP1
          valueFrom:
            configMapKeyRef:
              key: CONFIGMAP1_FROM_CONFIGMAP
              name: nodejs-app-demo-k8s-hpa-configmap
        - name: CONFIGMAP2
          valueFrom:
            configMapKeyRef:
              key: CONFIGMAP2_FROM_CONFIGMAP
              name: nodejs-app-demo-k8s-hpa-configmap
      resources:
        requests:
          cpu: ".2m"
        limits:
          cpu: ".5m"
