apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nodejs-app-demo-k8s-hpa
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nodejs-app-demo-k8s-hpa-deployment
status:
  currentReplicas: 0
  desiredReplicas: 0
