apiVersion: v1
data:
  password: "pwd here in base encoded"
stringData:
  key1: "k8s-pv-demo-secret-key1"
  key2: "k8s-pv-demo-secret-key2"
kind: Secret
metadata:
  name: k8s-pv-demo-secret
type: Opaque
