apiVersion: v1
kind: Pod
metadata:
  name: nodejs-app-demo-k8s-secret-pod
  labels:
    app: nodejs-app-demo-k8s-secret
spec:
  imagePullSecrets:
    - name: sample-regcred
  containers:
    - name: nodejs-app-demo-k8s-secret
      image: sdubey321/sdubey321-private-repo:1.1.0
      ports:
        - containerPort: 3000
      env:
        - name: DB_PASSWORD_NODE_DEMO
          valueFrom:
            secretKeyRef:
              key: password
              name: nodejs-app-demo-k8s-secret
        - name: PORT
          valueFrom:
            configMapKeyRef:
              key: PORT_FROM_CONFIGMAP
              name: nodejs-app-demo-config-configmap
        - name: APP_NAME
          valueFrom:
            configMapKeyRef:
              key: APP_NAME_FORM_CONFIGMAP
              name: nodejs-app-demo-config-configmap
        - name: CONFIGMAP1
          valueFrom:
            configMapKeyRef:
              key: CONFIGMAP1_FROM_CONFIGMAP
              name: nodejs-app-demo-config-configmap
        - name: CONFIGMAP2
          valueFrom:
            configMapKeyRef:
              key: CONFIGMAP2_FROM_CONFIGMAP
              name: nodejs-app-demo-config-configmap
