apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-demo-k8s-secret-service
spec:
  type: NodePort
  selector:
    app: nodejs-app-demo-k8s-secret
  ports:
    - port: 80
      targetPort: 3000
