apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92Mi8iOnsidXNlcm5hbWUiOiJzZHViZXkzMjEiLCJwYXNzd29yZCI6ImRja3JfcGF0X0RPRmRqd0lzWnkzYjEyWFhCdW53ZmNCNXNMWSIsImVtYWlsIjoic2R1YmV5MDIwMUBnbWFpbC5jb20iLCJhdXRoIjoiYzJSMVltVjVNekl4T21SamEzSmZjR0YwWDBSUFJtUnFkMGx6V25rellqRXlXRmhDZFc1M1ptTkNOWE5NV1E9PSJ9fX0=
kind: Secret
metadata:
  creationTimestamp: null
  name: sample-docker-secret
type: kubernetes.io/dockerconfigjson
