apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJzZHViZXkzMjEiLCJwYXNzd29yZCI6ImRja3JfcGF0X1piMnBNUGt3RHIxX3FMMEh4eDJwY1k4Z0V5byIsImVtYWlsIjoic2R1YmV5MDIwMUBnbWFpbC5jb20iLCJhdXRoIjoiYzJSMVltVjVNekl4T21SamEzSmZjR0YwWDFwaU1uQk5VR3QzUkhJeFgzRk1NRWg0ZURKd1kxazRaMFY1Ync9PSJ9fX0=
kind: Secret
metadata:
  creationTimestamp: null
  name: sample-docker-secret
type: kubernetes.io/dockerconfigjson
